Repository Team-Offroad/Offroad-Android, pull requests merged in 2024-09, with the labels that each got.

#149 refactor: navOptions 정리
  core/common/src/main/java/com/teamoffroad/core/common/util/OnBackButtonListener.kt
  core/common/src/main/res/values/strings.xml
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#155 feature: 네비게이션바 판단
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/GestureNavigation.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCharacterScreen.kt
Labels: 🍯 feature, ✨ 북두파 정현

#151 feature: 획득 쿠폰 UI
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NavigateBackAppBar.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/mapper/EmblemMapper.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/model/UsersAdventuresInformationEntity.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/UsersAdventuresInformationResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/service/UserService.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/repository/UserRepositoryImpl.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/model/UsersAdventuresInformation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/repository/UserRepository.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/usecase/UserUseCase.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MypageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireCharacter.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireEmblem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCoupon.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UseAvailableCouponDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserSettings.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/CheckCouponState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/FakeGainedCouponModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedCouponUiState.kt
  feature/mypage/src/main/res/drawable/ic_my_page_coupon_locked.xml
  feature/mypage/src/main/res/drawable/ic_my_page_error.xml
  feature/mypage/src/main/res/drawable/ic_mypage_close.xml
  feature/mypage/src/main/res/drawable/img_mypage_coupon.png
  feature/mypage/src/main/res/drawable/img_mypage_gained_coupon.png
  feature/mypage/src/main/res/drawable/img_mypage_way_of_use.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, ✨ 북두파 정현

#160 feature: Add mypage api
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/RepositoryModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/MyPageUserMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/MyPageUserEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/MyPageUserResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/UserService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/MyPageUserImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/MyPageUser.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/MyPageUserRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/MyPageUserUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/getErrorMessage.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/ErrorMessageModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/FakeUserModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/MyPageUiState.kt
Labels: 🍯 feature, ✨ 북두파 정현

#165 feature: 등록장소 서버 리팩토링 변경 대응
  .idea/other.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/PlaceService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/PlaceRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/PlaceRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetPlaceListUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
Labels: 🍯 feature, 🐤 참새파 준서

#166 feature: 칭호 조회 api 연결
  .idea/other.xml
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/RepositoryModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/EmblemMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/request/DeleteUserInfoRequestDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/request/MarketingInfoRequestDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/DeleteUserInfoResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/GainedEmblemResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/GainedEmblemsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/MarketingInfoResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/NotGainedEmblemResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/EmblemService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/UserService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/GainedEmblemsRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/MyPageUserImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/GainedEmblem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/GainedEmblemsRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/MyPageUserRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/DeleteUserInfoUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/UserEmblemsUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/UserMarketingInfoUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireEmblem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AnnouncementDetailHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/EmblemContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedEmblemsHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedEmblemsItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/LogoutDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/MarketingInfoDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingDialogState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserSettings.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithdrawTextField.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedEmblemsResult.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedEmblemsUiState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/SettingUiState.kt
  feature/mypage/src/main/res/drawable/ic_announcement_tag.xml
  feature/mypage/src/main/res/drawable/ic_my_page_emblems_lock.xml
  feature/mypage/src/main/res/drawable/ic_my_page_emblems_new.xml
  feature/mypage/src/main/res/drawable/ic_my_page_emblems_tag.xml
  feature/mypage/src/main/res/drawable/ic_setting_next.xml
  feature/mypage/src/main/res/drawable/ic_setting_tag.xml
  gradle/libs.versions.toml
Labels: 🍯 feature, 🐴 말왕파 석찬

#164 feature: 퀘스트 목록 조회 API 연결
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/NetworkModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/RepositoryModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/UseCaseModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/PlaceMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/QuestMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/UserMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/QuestResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/QuestsResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/PlaceService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/QuestService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/UserService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/ExploreRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/PlaceRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/QuestRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/UserRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/Quest.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/ExploreRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/PlaceRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/QuestRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/UserRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetPlaceListUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetQuestListUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/PostExploreLocationAuthUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/PostExploreQrAuthUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreRefreshButton.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSwitch.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestHeader.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/mapper/QuestMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/FakeQuestModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceCategory.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/QuestModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/QuestUiState.kt
Labels: 🍯 feature, 🐤 참새파 준서

#171 feature: 캐릭터 상세뷰 및 모션 구현
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/RepositoryModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/CharacterMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/MotionMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/CharacterDetailResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/MotionsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/CharacterService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/MotionService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/CharacterRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/MotionRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/CharacterDetail.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/CharacterMotion.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/CharacterRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/MotionRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/GetCharacterDetailUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/GetCharacterMotionListUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/CharacterDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/CharacterDetailViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCharacterScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDescriptionContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDetailImageItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterMotionsContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/RepresentativeUpdateResultSnackBar.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UpdateRepresentativeCharacterButton.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/mapper/CharacterMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/mapper/MotionMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/CharacterCategory.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/CharacterDetailUiModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/CharacterDetailUiState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedCharacterUiModel.kt
  feature/mypage/src/main/res/drawable/ic_my_page_success.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서

#173 refactor: 성공 다이알로그 디자인을 수정합니다
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreResultDialog.kt
  feature/explore/src/main/res/drawable-xhdpi/bg_explore_dialog.png
  feature/explore/src/main/res/drawable-xxhdpi/bg_explore_dialog.png
  feature/explore/src/main/res/drawable/bg_explore_dialog.png
Labels: ♻️ refactor, 🐤 참새파 준서

#172 refactor: 위치 인증 로직 수정
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/UserMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/ExploreLocationAuthResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/UserRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/ExploreLocationResult.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCamera.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreMapForeground.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreResultDialog.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreAuthState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreResultState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExploreAuthStateHandler.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExplorePermissionHandler.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExplorePermissionRejectedHandler.kt
  feature/explore/src/main/res/drawable-xhdpi/bg_explore_dialog.png
  feature/explore/src/main/res/drawable-xxhdpi/bg_explore_dialog.png
  feature/explore/src/main/res/drawable/bg_explore_dialog.png
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#179 feature: 성공 다이얼로그 띄우기
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CompleteQuestDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/DialogCloseButton.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/DialogConfirmButton.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/user/NicknameText.kt
  feature/home/src/main/res/values/strings.xml
Labels: 🍯 feature, ✨ 북두파 정현

#174 fix: 토큰 인증 오류 해결
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/DefaultTokenPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/TokenPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/AuthModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/DataModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/DataStoreModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/NetworkModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/RepositoryModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/TokenModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/UseCaseModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/local/AuthAuthenticator.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/local/AuthInterceptor.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/local/TokenManager.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/repository/TokenRepositoryImpl.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/repository/TokenRepository.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/usecase/ClearTokensUseCase.kt
  core/designsystem/src/main/res/values/themes.xml
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/datasource/AuthPreferencesDataSource.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/datasource/DefaultAuthPreferencesDataSource.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/DataModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/DataStoreModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/UseCaseModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/AuthRepositoryImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/repository/AuthRepository.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/AuthUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/ClearDataStoreUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetCharacterListUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/SetCharacterUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/UpdateAutoSignInUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/UpdateCharacterUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/UserMarketingAgreeUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
Labels: 🔨 fix, 🐤 참새파 준서

#170 feature: 쿠폰 목록 및 쿠폰 사용 api 연결
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/RepositoryModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/UserCouponMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/UserCouponsEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/request/UseCouponRequestDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/UseCouponResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/UserCouponsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/UserCouponService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/UserCouponRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/UseCoupon.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/UserCouponList.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/UserCouponRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/UserCouponListUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/ErrorMessage.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UseAvailableCouponDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedCouponUiState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/UiState.kt
  feature/mypage/src/main/res/drawable/img_coupon_new.png
Labels: 🍯 feature, ✨ 북두파 정현

#178 feature: 대표캐릭터 변경 추가
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/GestureNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/RepositoryModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/MyPageUserEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/UserCouponsEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/DeleteUserInfoResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/GainedEmblemResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/GainedEmblemsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/MyPageUserResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/NotGainedEmblemResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/UseCouponResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/UserCouponsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/UserCouponService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/UserCouponRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/GainedEmblem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/MyPageUser.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/UserCouponList.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/UserCouponListUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/CharacterDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/CharacterDetailViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCharacterScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDescriptionContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/EmblemContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UseAvailableCouponDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/ErrorMessageModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/FakeGainedCouponModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedEmblemsResult.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/UiState.kt
Labels: 🍯 feature, 🐤 참새파 준서

#181 refactor: 설정 ui 리플효과 추가
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquiredCharacter.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCoupon.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingContainer.kt
Labels: ♻️ refactor, 🐴 말왕파 석찬

#185 feature: 전환 애니메이션 제거
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsScreen.kt
Labels: 🍯 feature, 🐤 참새파 준서

#187 refactor: onboarding navigationPadding 수정
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsAllAgreeBox.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsItem.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsTopBar.kt
  feature/auth/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AnnouncementDetailHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedEmblemsHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/LogoutDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/MarketingInfoDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: ♻️ refactor, 🐴 말왕파 석찬

#189 refactor: 약관동의, 닉네임, 생년월일 qa
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/AuthRepositoryImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/repository/AuthRepository.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetBirthDateValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetNicknameValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
Labels: ♻️ refactor, 🐴 말왕파 석찬

#195 feature: 공지사항 api 연결
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/RepositoryModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/AnnouncementMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/EmblemMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/AnnouncementService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/AnnouncementRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/Announcement.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/AnnouncementRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/GetAnnouncementUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AnnouncementItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/LogoutDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/MarketingInfoDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithdrawTextField.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/AnnouncementResult.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/AnnouncementUiState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedEmblemsResult.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#197 refactor: 홈, 쿠폰 페이지 QA 대응
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CompleteQuestDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/ChangeEmblemDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CloseCompleteQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/RecentQuest.kt
  feature/home/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#198 refactor: Edit mypage character image url
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/UserMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/MyPageUserEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/MyPageUserResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/UserRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/MyPageUser.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/FakeGainedCouponModel.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#194 refactor: 장소 목록 QA 대응
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/ExpandableItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/PlaceMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/PlaceResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/Place.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceViewPager.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/mapper/ExploreMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/FakePlaceModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceUiState.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#199 refactor: 퀘스트 목록 반대로
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetQuestListUseCase.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#200 refactor: 로티 이미지 삭제
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterFrameItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterMotionsContainer.kt
Labels: ♻️ refactor, 🐤 참새파 준서
