Repository Team-Offroad/Offroad-Android, pull requests merged in 2024-11, with the labels that each got.

#206 feature: Transit OffroadActionBar to Modifier
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/OffroadActionBar.kt
Labels: 🍯 feature, 🐤 참새파 준서

#211 refactor: style guide 수정
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CircleProgressBar.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UpdateRepresentativeCharacterButton.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UseAvailableCouponDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#201 feature: 카카오로그인+스플래시 수정
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/datasource/DefaultAuthPreferencesDataSource.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/model/SocialSignInPlatform.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AuthUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SocialSignInPlatform.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/SplashScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  gradle/libs.versions.toml
Labels: 🍯 feature

#203 feature: Process Phoenix 추가
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamoffroad/offroad.app/OffroadApplication.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/AutoSignInPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/DefaultAutoSignInPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/AuthModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/DataModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/DataStoreModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/NetworkModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/RepositoryModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/UseCaseModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/qualifier/Qualifier.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/local/AuthAuthenticator.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/repository/AutoSignInRepositoryImpl.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/repository/AutoSignInRepository.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/usecase/GetAutoSignInUseCase.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/usecase/SetAutoSignInUseCase.kt
  core/common/src/main/java/com/teamoffroad/core/common/intentProvider/IntentProvider.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/DataModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/DataStoreModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/KakaoAuthModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/NetworkModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/OAuthInteractorModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/UseCaseModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/AuthRepositoryImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/OAuthInteractorImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/repository/AuthRepository.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/repository/OAuthInteractor.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetAutoSignInUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/UpdateAutoSignInUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/OAuthEntryPoint.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AuthUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/NetworkModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/NetworkModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/di/IntentModule.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/intentprovider/IntentProviderImpl.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/NetworkModule.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/LogoutDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/SettingUiState.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🍯 feature, 🐴 말왕파 석찬

#220 feature: 온보딩, 칭호, 설정 페이지 디자인 수정
  .idea/other.xml
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NoRippleClickable.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/UseCaseModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/model/ValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/DayValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetBirthDateValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/MonthValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/YearValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsAllAgreeBox.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/DateValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OffroadBasicButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetCharacterDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetNicknameButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/ShowSetCharacterPager.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetBirthDateUiState.kt
  feature/auth/src/main/res/drawable/ic_agree_check_fill.xml
  feature/auth/src/main/res/drawable/ic_app_logo.xml
  feature/auth/src/main/res/drawable/ic_auth_logo.xml
  feature/auth/src/main/res/drawable/ic_splash_logo.png
  feature/auth/src/main/res/values/strings.xml
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/SplashScreen.kt
  feature/main/src/main/res/drawable/ic_splash_app_logo.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/AnnouncementMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/Announcement.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AnnouncementItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/EmblemContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedEmblemsItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/LogoutDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/MarketingInfoDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/res/drawable/ic_announcement_tag.xml
  feature/mypage/src/main/res/drawable/ic_my_page_check_circle.xml
  feature/mypage/src/main/res/drawable/ic_my_page_emblems_new.xml
  feature/mypage/src/main/res/drawable/ic_my_page_emblems_tag.xml
  feature/mypage/src/main/res/drawable/ic_setting_tag.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: ♻️ refactor, 🐴 말왕파 석찬

#224 feature: 로딩, 에러 로티
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AuthUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetCharacterUiState.kt
  feature/auth/src/main/res/drawable-xhdpi/ic_splash_logo.png
  feature/auth/src/main/res/drawable-xxhdpi/ic_splash_logo.png
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/SplashScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/SplashScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/SplashUiState.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/SplashViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/navigation/SplashNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedEmblemsUiState.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#227 feature: 캐릭터 채팅 UI 구현
  .idea/other.xml
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/GestureNavigation.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NavigateBackAppBar.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/navigation/CharacterChatNavigation.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatHeader.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChats.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatButton.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatTextBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatTextField.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/DateDivider.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ImePadding.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/TimeLabel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/UserChatBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiState.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/ChatType.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/gitkeep
  feature/characterchat/src/main/res/drawable/ic_character_chat_send.xml
  feature/characterchat/src/main/res/values/strings.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreAppBar.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/CharacterDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDetailAppBar.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서

#229 feature: 캐릭터 채팅 API 구현
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/di/NetworkModule.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/di/RepositoryModule.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/di/UseCaseModule.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/di/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/mapper/CharacterChatMapper.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/mapper/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/model/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/request/CharacterChatSendRequestDto.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/response/CharacterChatResponseDto.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/service/ChatService.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/repository/CharacterChatRepositoryImpl.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/repository/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/model/Chat.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/model/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/repository/CharacterChatRepository.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/repository/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/GetChatListUseCase.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/PostChatUseCase.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/gitkeep
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/navigation/CharacterChatNavigation.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatTextField.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/DateDivider.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/TimeLabel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/UserChatBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/mapper/CharacterChatMapper.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiState.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/ChatType.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/TimeType.kt
  feature/characterchat/src/main/res/drawable/bg_character_chat.png
  feature/characterchat/src/main/res/values/strings.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreAppBar.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/CharacterDetailScreen.kt
Labels: 🍯 feature, 🐤 참새파 준서

#234 feature: 로딩 로티 적용
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/CircularLoadingAnimation.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/FullLinearLoadingAnimation.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/LinearLoadingAnimation.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChats.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatButton.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
Labels: 🍯 feature, 🐤 참새파 준서

#226 refactor: Edit design system
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItem.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#217 feature: 이미지 공유 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/file_paths.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/download/DownloadImage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/upload/UploadImage.kt
  feature/home/src/main/res/values/strings.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavTab.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/main/src/main/res/drawable/ic_main_home_active.xml
  feature/main/src/main/res/drawable/ic_main_home_inactvie.xml
  feature/main/src/main/res/drawable/ic_main_my_page_active.xml
  feature/main/src/main/res/drawable/ic_main_my_page_inactive.xml
  gradle/libs.versions.toml
Labels: 🍯 feature, ✨ 북두파 정현

#240 fix: 추가 쿠폰 로딩 오류 해결
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/UiState.kt
Labels: 🔨 fix, 🐤 참새파 준서

#236 feature: 퀘스트 및 장소 뷰 무한스크롤 구현
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/CircularLoadingAnimationLine.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/QuestMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/QuestResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/QuestService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/QuestRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/Quest.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/QuestRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetQuestListUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceViewPager.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/mapper/QuestMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/QuestModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/QuestUiState.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/UiState.kt
Labels: 🍯 feature, 🐤 참새파 준서

#238 fix: 탐험 뷰 터치 영역 수정
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
Labels: 🔨 fix, 🐤 참새파 준서

#242 refactor: 채팅 뷰 컴포넌트 수정
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatTextBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ImePadding.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/TimeLabel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/UserChatBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiModel.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#245 feature: 서버 이미지 대응 컴포넌트 제작
  build-logic/convention/src/main/java/AndroidFeatureConventionPlugin.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/AdaptationImage.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/ShowSetCharacterPager.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSuccessDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItem.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDescriptionContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDetailImageItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterFrameItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  gradle/libs.versions.toml
Labels: 🍯 feature, 🐤 참새파 준서

#233 feature: 푸시알림
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamoffroad/offroad.app/OffRoadMessagingService.kt
  app/src/main/java/com/teamoffroad/offroad.app/OffroadApplication.kt
  build-logic/convention/src/main/java/AndroidApplicationConventionPlugin.kt
  build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/AutoSignInPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/DefaultTokenPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/datasource/TokenPreferencesDataSource.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/DataStoreModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/local/AuthAuthenticator.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/repository/AutoSignInRepositoryImpl.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/repository/TokenRepositoryImpl.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/model/FcmNotificationKey.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/model/NotificationEvent.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/repository/TokenRepository.kt
  core/common/src/main/java/com/teamoffroad/core/common/util/ActivityLifecycleHandler.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AuthUiState.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/NetworkModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/RepositoryModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/UseCaseModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/request/FcmTokenRequestDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/request/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/service/FcmTokenService.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/repository/FcmTokenRepositoryImpl.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/repository/FcmTokenRepository.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/usecase/PostFcmTokenUseCase.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/CharacterChatBroadcastReceiver.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainUiState.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/SplashScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/SplashUiState.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/SplashViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/splash/navigation/SplashNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/AnnouncementMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/Announcement.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedEmblemsViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedEmblemsItems.kt
  gradle/libs.versions.toml
Labels: 🍯 feature, 🐴 말왕파 석찬

#255 refactor: 브로드캐스트 위치 변경
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/MainViewModel.kt
Labels: ♻️ refactor, 🐴 말왕파 석찬

#250 feature: 앱 아이콘 및 이름 리브랜딩 반영
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/offroad_logo_light.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서

#251 feature: 퀘스트목록 2차 스프린트 1차 QA 반영
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
Labels: 🍯 feature, 🐤 참새파 준서

#252 feature: 캐릭터상세 2차 스프린트 1차 QA 반영
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/CharacterMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/UserMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/CharacterDetailResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDescriptionContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterDetailImageItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterFrameItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UpdateRepresentativeCharacterButton.kt
  feature/mypage/src/main/res/drawable/ic_my_page_new.xml
  feature/mypage/src/main/res/drawable/ic_my_page_representative.xml
Labels: 🍯 feature, 🐤 참새파 준서

#243 feature: 홈 채팅 구현
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/CharacterChatModel.kt
  feature/home/src/main/res/drawable/ic_home_accordian.xml
  feature/home/src/main/res/values/strings.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/CharacterChattingUiState.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/UserChattingUiState.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/CharacterChat.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/UserChat.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/UserChatTextField.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/UserCouponMapper.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/UserAvailableCouponsEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/model/UserUsedCouponsEntity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/UserAvailableCouponsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/UserUsedCouponsResponseDto.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/service/UserCouponService.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/UserCouponRepositoryImpl.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/UserAvailableCoupons.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/model/UserUsedCoupons.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/UserCouponRepository.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/usecase/UserCouponListUseCase.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UseAvailableCouponDialog.kt
  feature/mypage/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🍯 feature, ✨ 북두파 정현

#253 feature: 채팅로그 2차 스프린트 1차 QA 반영
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/LinearLoadingAnimation.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/service/ChatService.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/repository/CharacterChatRepositoryImpl.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/repository/CharacterChatRepository.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/GetChatListUseCase.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/PostChatUseCase.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/navigation/CharacterChatNavigation.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatLoadingBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChats.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiState.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
Labels: 🍯 feature, 🐤 참새파 준서
