Repository Team-Offroad/Offroad-Android, pull requests merged in 2024-12, with the labels that each got.

#266 refactor: 온보딩 qa
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/DayValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetNicknameValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AgreeTermsAndConditionsViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsItem.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/DialogScrollBar.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/GenderHintButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/ShowSetCharacterPager.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AgreeTermsAndConditionsUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AuthUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/DateValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/NicknameValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetBirthDateUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetGenderUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetNicknameUiState.kt
  feature/auth/src/main/res/drawable/ic_agree_check_empty.xml
Labels: ♻️ refactor

#267 refactor: 설정, 칭호 qa
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/EmblemContainer.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/LogoutDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithdrawTextField.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/SettingUiState.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: ♻️ refactor

#269 refactor: migration Google OAuth2 to Credential
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/GoogleAuthModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/SocialAuthModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/OAuthInteractorImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/repository/OAuthInteractor.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/AuthUiState.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  gradle/libs.versions.toml
Labels: ♻️ refactor

#270 refactor: 마이페이지 및 쿠폰 QA 대응
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OffroadBasicButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetCharacterDialog.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CompleteQuestDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/ChangeEmblemDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/DialogConfirmButton.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/DrawTitleDialogScrollBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/LinearProgressBar.kt
  feature/home/src/main/res/drawable/ic_home_change.xml
  feature/home/src/main/res/drawable/ic_home_change_character.xml
  feature/home/src/main/res/drawable/img_home_background.png
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AvailableCouponDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCouponViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCouponViewPager.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/CouponListUiState.kt
Labels: ♻️ refactor, ✨ 북두파 정현, 📄 QA 대응

#276 feature: 장소목록 2차 스프린트 2차 QA 반영
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/UseCaseModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/PlaceService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/PlaceRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/PlaceRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetPlaceListUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceViewPager.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlacePage.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceUiState.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐤 참새파 준서, 📄 QA 대응

#272 feature: 퀘스트목록 2차 스프린트 2차 QA 반영
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/ExpandableItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItem.kt
Labels: 🍯 feature, 🐤 참새파 준서, 📄 QA 대응

#271 feature: 캐릭터목록 2차 스프린트 2차 QA 반영
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCharacterScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCharacterHeader.kt
  feature/mypage/src/main/res/drawable/ic_my_page_character.xml
Labels: 🍯 feature, 🐤 참새파 준서, 📄 QA 대응

#280 feature: 고객문의 및 지도 약관 추가
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NavigateBackAppBar.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SupportScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingHeader.kt
  feature/mypage/src/main/res/drawable/ic_customer_support.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서

#279 feature: 홈 채팅 QA 반영
  feature/characterchat/build.gradle.kts
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/mapper/CharacterChatMapper.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/response/CharacterChatLastUnreadResponseDto.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/service/ChatService.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/repository/CharacterChatRepositoryImpl.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/model/ChatLastUnread.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/repository/CharacterChatRepository.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/GetChatLastUnreadUseCase.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/MainCharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatTextField.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainCharacterChat.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainUserChat.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainUserChatTextField.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatLastUnreadUiState.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChattingUiState.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/UiState.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/UserChattingUiState.kt
  feature/characterchat/src/main/res/drawable/ic_home_accordian.xml
  feature/characterchat/src/main/res/values/strings.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/res/values/strings.xml
  feature/main/build.gradle.kts
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: ♻️ refactor, ✨ 북두파 정현, 📄 QA 대응

#274 feature: 채팅로그 2차 스프린트 2차 QA 반영
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/mapper/CharacterChatMapper.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/response/CharacterChatResponseDto.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/remote/service/ChatService.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/data/repository/CharacterChatRepositoryImpl.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/model/Chat.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/repository/CharacterChatRepository.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/domain/usecase/GetChatListUseCase.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatScreen.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatLoadingBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChats.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ChatButton.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/mapper/CharacterChatMapper.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/model/CharacterChatUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
Labels: 🍯 feature, 🐤 참새파 준서, 📄 QA 대응

#283 fix: 카카오 소셜 로그인 오류 해결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamoffroad/offroad.app/OffroadApplication.kt
Labels: 🔨 fix, 🐤 참새파 준서

#285 refactor: 프로필 업데이트 api 수정
  .idea/other.xml
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/UseCaseModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/mapper/AuthMapper.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/remote/request/ProfileUpdateRequestDto.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/remote/service/AuthService.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/AuthRepositoryImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/model/UserGender.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/model/UserProfile.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/repository/AuthRepository.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/PatchUserProfileUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetBirthDateUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetGenderUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetNicknameUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signin/OAuthEntryPoint.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signin/SignInScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signin/SignInUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signin/SignInViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/BirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/GenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/NicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SetCharacterViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/termandcondition/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/termandcondition/AgreeTermsAndConditionsUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/termandcondition/AgreeTermsAndConditionsViewModel.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: ♻️ refactor

#284 refactor: 설정, 공지사항 ui 디테일
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetNicknameValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
  feature/characterchat/src/androidTest/java/com/teamoffroad/characterchat/ExampleInstrumentedTest.kt
  feature/characterchat/src/test/java/com/teamoffroad/characterchat/ExampleUnitTest.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AnnouncementItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/SettingItems.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/SettingItem.kt
Labels: ♻️ refactor

#288 feature: 약관동의 뷰 3차 QA 반영
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsItem.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OffroadBasicButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/termandcondition/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서, 📄 QA 대응

#290 feature: 지도 SDK 정책 반영
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/AdaptationImage.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExploreAuthStateHandler.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExplorePermissionHandler.kt
  feature/explore/src/main/res/drawable/bg_explore_info_window_arrow.xml
  feature/explore/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🍯 feature, 🐤 참새파 준서

#289 refactor: 모험가 프로필 작성(닉네임) 3차 QA
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetNicknameValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OffroadBasicButton.kt
Labels: ♻️ refactor, ✨ 북두파 정현, 📄 QA 대응

#295 refactor: 3차 qa
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetCharacterDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SignUpPage.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/BirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/GenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpViewModel.kt
  feature/auth/src/main/res/drawable/bg_auth_selected_character_light.png
  feature/auth/src/main/res/drawable/img_test_character.xml
  feature/auth/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AnnouncementItems.kt
Labels: ♻️ refactor

#296 feature: 홈->캐릭터챗 이동 구현
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/navigation/CharacterChatNavigation.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainCharacterChat.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐤 참새파 준서

#299 refactor: 생년월일 텍스트필드 포커스 이동조건
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/BirthDateFocus.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/BirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpViewModel.kt
Labels: ♻️ refactor

#300 refactor: 3차 QA 추가 수정사항 반영
  README.md
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/AgreeTermsAndConditionsItem.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OffroadBasicButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signin/SignInScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/BirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/termandcondition/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/res/values/strings.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/UserMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/ExploreLocationAuthResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/UserRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/ExploreLocationResult.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreAuthState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExploreAuthStateHandler.kt
  feature/explore/src/main/res/drawable/ic_explore_fail.xml
  feature/explore/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithDrawDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/WithdrawTextField.kt
  feature/mypage/src/main/res/drawable/ic_my_page_success.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: ♻️ refactor, 🐤 참새파 준서

#302 fix: 구글 로그인 오류 해결
  app/src/main/AndroidManifest.xml
  core/common/src/main/java/com/teamoffroad/core/common/data/di/AuthModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/local/AuthAuthenticator.kt
  core/common/src/main/java/com/teamoffroad/core/common/util/IntentProvider.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/OAuthInteractorImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/GenderHintButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signin/SignInScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/BirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/signup/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/termandcondition/AgreeTermsAndConditionsScreen.kt
  feature/auth/src/main/res/values/strings.xml
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/LinearProgressBar.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/SplashScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/di/IntentModule.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/intentprovider/IntentProviderImpl.kt
  feature/mypage/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🔨 fix, 🐤 참새파 준서
