Repository Team-Offroad/Offroad-Android, pull requests merged in 2024-08, with the labels that each got.

#123 refactor: 탐험 뷰 1차 QA 반영
  .idea/other.xml
  core/common/src/main/java/com/teamoffroad/core/common/data/local/AuthInterceptor.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NoRippleClickable.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCamera.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreResultDialog.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreCameraUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreResultState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExploreCameraUiStateHandler.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExploreLocationPermissionHandler.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/ExplorePermissionRejectedHandler.kt
  feature/explore/src/main/res/drawable-xhdpi/bg_explore_info_window.png
  feature/explore/src/main/res/drawable-xxhdpi/bg_explore_info_window.png
  feature/explore/src/main/res/drawable/bg_explore_info_window.png
  feature/explore/src/main/res/drawable/ic_explore_error_code.xml
  feature/explore/src/main/res/drawable/ic_explore_error_location.xml
  feature/explore/src/main/res/drawable/ic_explore_info_window_logo.xml
  feature/explore/src/main/res/values/strings.xml
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  gradle/libs.versions.toml
Labels: ♻️ refactor, 🐤 참새파 준서

#113 refactor: Remove unused extension
  build-logic/convention/src/main/java/com/teamoffroad/app/ApiKeyExtension.kt
  core/common/build.gradle.kts
  feature/auth/build.gradle.kts
Labels: ♻️ refactor, 🐤 참새파 준서

#139 feature: 추가된 디자인 시스템 대응
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
Labels: 🍯 feature, 🐤 참새파 준서

#145 refactor: 2차 QA 수정
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/model/UserGender.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetBirthDateValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetCharacterIndicator.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/ShowSetCharacterPager.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
Labels: ♻️ refactor, 🐴 말왕파 석찬

#144 Feature: mypage ui
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MypageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageViewModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireCharacter.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireCoupon.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireEmblem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserSettings.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/FakeUserModel.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/MyPageUiState.kt
  feature/mypage/src/main/res/drawable/img_emblem_tag.xml
  feature/mypage/src/main/res/drawable/img_flag.xml
  feature/mypage/src/main/res/drawable/img_line.png
  feature/mypage/src/main/res/drawable/img_mypage_acquire_character.png
  feature/mypage/src/main/res/drawable/img_mypage_acquire_coupon.png
  feature/mypage/src/main/res/drawable/img_mypage_acquire_emblem.png
  feature/mypage/src/main/res/drawable/img_mypage_user_settings.png
  feature/mypage/src/main/res/drawable/test_img_user_home.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, ✨ 북두파 정현

#147 feature: 획득 캐릭터 목록 UI 구현
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NoRippleClickable.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MypageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCharacterScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterFrameItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCharacterHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedCharacterUiModel.kt
  feature/mypage/src/main/res/drawable/ic_my_page_character.xml
  feature/mypage/src/main/res/drawable/ic_my_page_character_locked.xml
  feature/mypage/src/main/res/drawable/ic_my_page_check_circle.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서

#143 feature: 퀘스트 목록 UI 구현
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/ExpandableItem.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSwitch.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestHeader.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/FakeQuestModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/QuestUiState.kt
  feature/explore/src/main/res/drawable/ic_explore_quest_reward.xml
  feature/explore/src/main/res/drawable/ic_explore_quest_task.xml
  feature/explore/src/main/res/values/strings.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐤 참새파 준서

#137 feature: 장소 목록 UI 구현
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/ExpandableItem.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NavigateBackAppBar.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/NoRippleClickable.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  core/designsystem/src/main/res/drawable/ic_expand.xml
  core/designsystem/src/main/res/drawable/ic_navigate_back.xml
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/PlaceScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/QuestViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreOffroadMap.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSwitch.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceHeader.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/PlaceViewPager.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestHeader.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/QuestItems.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/mapper/ExploreMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/FakePlaceModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/FakeQuestModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceCategory.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/QuestUiState.kt
  feature/explore/src/main/res/drawable/ic_explore_quest_reward.xml
  feature/explore/src/main/res/drawable/ic_explore_quest_task.xml
  feature/explore/src/main/res/drawable/ic_explore_scroll.xml
  feature/explore/src/main/res/values/strings.xml
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavTab.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/main/src/main/res/drawable/ic_main_my_page.xml
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MypageNavigation.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/GainedCharacterScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/AcquireCharacter.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/CharacterFrameItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/GainedCharacterHeader.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/UserItem.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/model/GainedCharacterUiModel.kt
  feature/mypage/src/main/res/drawable/ic_my_page_character.xml
  feature/mypage/src/main/res/drawable/ic_my_page_character_locked.xml
  feature/mypage/src/main/res/drawable/ic_my_page_check_circle.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서
