Repository Team-Offroad/Offroad-Android, pull requests merged in 2024-07, with the labels that each got.

#6 docs: add issue and pull request template
  .github/ISSUE_TEMPLATE/default_issue_template.md
  .github/pull_request_template.md
Labels: 📄 docs, ✨ 북두파 정현

#8 refactor: feature별 모듈 분리 마이그레이션
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/java/AndroidFeatureConventionPlugin.kt
  build-logic/convention/src/main/java/AndroidHiltConventionPlugin.kt
  build-logic/convention/src/main/java/KotlinHiltConventionPlugin.kt
  build-logic/convention/src/main/java/com/teamoffroad/app/AppNameExtension.kt
  build-logic/convention/src/main/java/com/teamoffroad/app/ComposeAndroid.kt
  build-logic/convention/src/main/java/com/teamoffroad/app/HiltAndroid.kt
  build-logic/convention/src/main/java/com/teamoffroad/app/HiltKotlin.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/data/di/NetworkModule.kt
  core/data/.gitignore
  core/data/build.gradle.kts
  core/data/src/main/AndroidManifest.xml
  core/data/src/main/java/com/teamoffroad/core/data/repository/gitkeep
  core/data/src/test/java/com/teamoffroad/core/data/ExampleUnitTest.kt
  core/database/.gitignore
  core/database/build.gradle.kts
  core/database/src/main/AndroidManifest.xml
  core/database/src/main/java/com/teamoffroad/core/database/dao/gitkeep
  core/database/src/main/java/com/teamoffroad/core/database/di/gitkeep
  core/database/src/main/java/com/teamoffroad/core/database/model/gitkeep
  core/database/src/main/java/com/teamoffroad/core/database/util/gitkeep
  core/database/src/test/java/com/teamoffroad/core/database/ExampleUnitTest.kt
  core/datastore/.gitignore
  core/datastore/build.gradle.kts
  core/datastore/src/main/AndroidManifest.xml
  core/datastore/src/test/java/com/teamoffroad/core.datastore/ExampleUnitTest.kt
  core/domain/.gitignore
  core/domain/build.gradle.kts
  core/domain/src/main/AndroidManifest.xml
  core/domain/src/main/java/com/teamoffroad/core/domain/entity/gitkeep
  core/domain/src/main/java/com/teamoffroad/core/domain/repository/gitkeep
  core/domain/src/main/java/com/teamoffroad/core/domain/usecase/gitkeep
  core/domain/src/test/java/com/teamoffroad/core/domain/ExampleUnitTest.kt
  core/model/.gitignore
  core/model/build.gradle.kts
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/src/main/AndroidManifest.xml
  core/network/src/test/java/com/teamoffroad/core/network/ExampleUnitTest.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/NetworkModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/RepositoryModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/UseCaseModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/mapper/DummyUserMapper.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/model/DummyUserEntity.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/request/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/DummyUserResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/service/DummyUserService.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/repository/DummyDummyUserRepositoryImpl.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/model/DummyUser.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/repository/DummyUserRepository.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/usecase/GetDummyUserListUseCase.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/navigation/gitkeep
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ♻️ refactor, 🐤 참새파 준서

#11 feature: 디자인 시스템 구성
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/optician_sans.otf
  core/designsystem/src/main/res/font/pretendard_bold.ttf
  core/designsystem/src/main/res/font/pretendard_medium.ttf
  core/designsystem/src/main/res/font/pretendard_regular.ttf
  core/designsystem/src/main/res/font/pretendard_semibold.ttf
Labels: 🍯 feature, ✨ 북두파 정현

#14 feature: Add auth to home navigation
  feature/auth/src/main/java/com/teamoffroad/feature/auth/AuthRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#18 refactor: 디자인 시스템 수정
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#25 feature: Add Custom Bottom Bar
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavTab.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/main/src/main/res/drawable/ic_main_explore.xml
  feature/main/src/main/res/drawable/ic_main_home.xml
  feature/main/src/main/res/drawable/ic_main_mypage.xml
  gradle/libs.versions.toml
Labels: 🍯 feature, ✨ 북두파 정현

#28 feature: Add api key extension
  build-logic/convention/src/main/java/com/teamoffroad/app/ApiKeyExtension.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/data/di/NetworkModule.kt
  feature/auth/build.gradle.kts
Labels: 🍯 feature, 🐴 말왕파 석찬

#32 feature: 위치 권한 기능 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build-logic/convention/src/main/java/AndroidApplicationConventionPlugin.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/teamoffroad/feature/explore/ExploreRoute.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreRoute.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/navigation/ExploreNavigation.kt
  feature/explore/src/main/res/values/strings.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🍯 feature, 🐤 참새파 준서

#31 feature: Add auth ui
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/AuthNavigation.kt
  feature/auth/src/main/res/drawable/ic_auth_google_logo.xml
  feature/auth/src/main/res/drawable/ic_auth_kakao_logo.xml
  feature/auth/src/main/res/drawable/ic_auth_logo.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#29 feature: Add home UI
  build-logic/convention/src/main/java/AndroidComposeConventionPlugin.kt
  build-logic/convention/src/main/java/com/teamoffroad/app/ComposeAndroid.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/OffroadTagItem.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CharacterImage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CharacterNameText.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/CloseCompleteQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/ContentsLocation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/ContentsTitle.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/EmblemNameText.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/LinearProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/NicknameText.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/RecentQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/HomeProgressBarModel.kt
  feature/home/src/main/res/drawable/ic_home_change.xml
  feature/home/src/main/res/drawable/ic_home_change_title.xml
  feature/home/src/main/res/drawable/ic_home_download.xml
  feature/home/src/main/res/drawable/ic_home_upload.xml
  feature/home/src/main/res/drawable/img_home_close_complete.xml
  feature/home/src/main/res/drawable/img_home_explorer.xml
  feature/home/src/main/res/drawable/img_home_recent_quest.xml
  feature/home/src/main/res/drawable/img_home_shadow.xml
  feature/home/src/main/res/drawable/img_home_stamp.xml
  feature/home/src/main/res/values/strings.xml
  feature/main/src/main/res/drawable/ic_main_explore.xml
Labels: 🍯 feature, ✨ 북두파 정현

#42 feature: 생년월일 설정 UI 추가
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetBirthDateNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetNicknameNavigation.kt
  feature/auth/src/main/res/drawable/btn_auth_back.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#45 feature: Add Coil library at feature gradle convention
  build-logic/convention/src/main/java/AndroidFeatureConventionPlugin.kt
  gradle/libs.versions.toml
Labels: 🍯 feature, 🐤 참새파 준서

#46 feature: 성별 설정 UI 추가
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/GenderHintButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetBirthDateNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetGenderNavigation.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#48 feature: 탐험 뷰 등록장소 추가
  core/common/src/main/java/com/teamoffroad/core/common/data/remote/response/BaseResponse.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/request/gitkeep
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/PlaceResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/gitkeep
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreRoute.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreMapForeground.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreRefreshButton.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreTrackingButton.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceCategory.kt
  feature/explore/src/main/res/drawable-xhdpi/bg_explore_info_window.png
  feature/explore/src/main/res/drawable-xxhdpi/bg_explore_info_window.png
  feature/explore/src/main/res/drawable/bg_explore_info_window.png
  feature/explore/src/main/res/drawable/bg_explore_info_window_triangle.xml
  feature/explore/src/main/res/drawable/ic_explore_info_window_close.xml
  feature/explore/src/main/res/drawable/ic_explore_place_marker.xml
  feature/explore/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐤 참새파 준서

#40 feature: 탐험 뷰 지도 UI 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamoffroad/offroad.app/OffroadApplication.kt
  app/src/test/java/com/teamoffroad/app/ExampleUnitTest.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/remote/response/BaseResponse.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/request/gitkeep
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/PlaceResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/gitkeep
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreRoute.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreAppBar.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreInfoWindow.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreMapBottomButton.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreMapForeground.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreRefreshButton.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreTrackingButton.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/PlaceCategory.kt
  feature/explore/src/main/res/drawable-xhdpi/bg_explore_info_window.png
  feature/explore/src/main/res/drawable-xhdpi/ic_explore_location_overlay.png
  feature/explore/src/main/res/drawable-xxhdpi/bg_explore_info_window.png
  feature/explore/src/main/res/drawable-xxhdpi/ic_explore_location_overlay.png
  feature/explore/src/main/res/drawable/bg_explore_info_window.png
  feature/explore/src/main/res/drawable/bg_explore_info_window_triangle.xml
  feature/explore/src/main/res/drawable/ic_explore_info_window_close.xml
  feature/explore/src/main/res/drawable/ic_explore_location.xml
  feature/explore/src/main/res/drawable/ic_explore_location_overlay.png
  feature/explore/src/main/res/drawable/ic_explore_location_overlay_sub.xml
  feature/explore/src/main/res/drawable/ic_explore_place_marker.xml
  feature/explore/src/main/res/drawable/ic_explore_quest_list.xml
  feature/explore/src/main/res/drawable/ic_explore_refresh.xml
  feature/explore/src/main/res/drawable/ic_explore_tracking_follow.xml
  feature/explore/src/main/res/drawable/ic_explore_tracking_no_follow.xml
  feature/explore/src/main/res/values/strings.xml
  feature/explore/src/test/java/com/teamoffroad/feature/explore/ExampleUnitTest.kt
Labels: 🍯 feature, 🐤 참새파 준서

#50 refactor: 홈 ui 수정
  feature/home/src/main/java/com/teamoffroad/feature/home/HomeScreen.kt
  feature/home/src/main/res/drawable/ic_home_download.xml
Labels: ♻️ refactor, ✨ 북두파 정현

#51 Feature: 홈 뷰 이미지 다운로드 기능 구현
  app/src/main/AndroidManifest.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeRoute.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/TitleDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/download/DownloadImage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/DownloadResult.kt
  feature/home/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🍯 feature, ✨ 북두파 정현

#65 fix: Resolve sign in lifecycle problem
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
Labels: 🍯 feature, 🐤 참새파 준서

#60 feature: User quests info api
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/data/mapper/EmblemMapper.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/model/UserQuestEntity.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/EmblemsResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/UserQuestsResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/service/EmblemService.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/repository/EmblemRepositoryImpl.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/model/UserQuests.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/repository/EmblemRepository.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/usecase/GetEmblemListUseCase.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/ErrorMessageModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/TitleDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/TitleDialogChangeButton.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/LinearProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/RecentQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/getErrorMessage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/HomeProgressBarModel.kt
  gradle/libs.versions.toml
Labels: 🍯 feature, ✨ 북두파 정현

#67 refactor: Connect users Adventures Informations api
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/NetworkModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/RepositoryModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/di/UseCaseModule.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/mapper/EmblemMapper.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/model/UsersAdventuresInformationsEntity.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/UsersAdventuresInformationsResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/service/UserService.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/repository/UserRepositoryImpl.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/model/UsersAdventuresInformations.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/repository/UserRepository.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/usecase/GetEmblemListUseCase.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/usecase/UserUseCase.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/download/DownloadImage.kt
Labels: 🍯 feature, ✨ 북두파 정현

#73 feature: 탐험 뷰 API 연결
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/NetworkModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/RepositoryModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/UseCaseModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/ExploreMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/request/ExploreAuthRequestDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/request/gitkeep
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/ExploreAuthResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/PlaceResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/PlacesResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/ExploreService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/gitkeep
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/ExploreRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/Place.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/ExploreRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/GetPlaceListUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/PostExploreAuthUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCamera.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCameraNavigateBack.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreResultDialog.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSuccessDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/mapper/ExploreMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreCameraUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/BarcodeAnalyzer.kt
  feature/explore/src/main/res/drawable-xhdpi/bg_explore_dialog.png
  feature/explore/src/main/res/drawable-xhdpi/img_explore_failed_character.png
  feature/explore/src/main/res/drawable-xxhdpi/bg_explore_dialog.png
  feature/explore/src/main/res/drawable-xxhdpi/img_explore_failed_character.png
  feature/explore/src/main/res/drawable/bg_explore_dialog.png
  feature/explore/src/main/res/drawable/ic_explore_error_code.xml
  feature/explore/src/main/res/drawable/ic_explore_error_location.xml
  feature/explore/src/main/res/drawable/img_explore_failed_character.png
  feature/explore/src/main/res/values/strings.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐤 참새파 준서

#75 feature: 온보딩 뷰 네비게이션 연결
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/OffroadBasicButton.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/mapper/AuthMapper.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/remote/request/ProfileUpdateRequestDto.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/remote/service/AuthService.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/repository/AuthRepositoryImpl.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/model/UserProfile.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/OnboardingViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameRoute.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetCharacterDialog.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetBirthDateNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetCharacterNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetGenderNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/navigation/SetNicknameNavigation.kt
  feature/auth/src/main/res/values/strings.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/gitkeep
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/navigation/gitkeep
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐤 참새파 준서

#77 refactor: 홈 ui 수정
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Type.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/DrawTitleDialogScrollBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/TitleDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/ContentsLocation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/ContentsTitle.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CloseCompleteQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/RecentQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/user/NicknameText.kt
  feature/home/src/main/res/drawable/ic_home_change_title.xml
  feature/home/src/main/res/drawable/img_home_stamp.xml
Labels: ♻️ refactor, ✨ 북두파 정현

#80 feature: 캐릭터 선택 ui 수정
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/theme/Color.kt
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SplashScreen.kt
  feature/auth/src/main/res/drawable/bg_auth_selected_character_light.png
  feature/auth/src/main/res/drawable/ic_splash_logo.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#82 feature: API 오류 해결
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/remote/service/AuthService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/ExploreMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/ExploreAuthResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/ExploreRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/ExploreResult.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/ExploreRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/PostExploreAuthUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCamera.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreResultDialog.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSuccessDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/model/ExploreUiState.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/util/BarcodeAnalyzer.kt
Labels: 🍯 feature, 🐤 참새파 준서

#79 feature: Add lottie files
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/teamoffroad/feature/home/data/mapper/EmblemMapper.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/model/UsersAdventuresInformationsEntity.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/UsersAdventuresInformationsResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/repository/UserRepositoryImpl.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/model/UsersAdventuresInformations.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeRoute.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  gradle/libs.versions.toml
Labels: 🍯 feature, ✨ 북두파 정현

#86 feature: 스플래시 및 화면 전환 애니메이션 수정
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/OffroadActionBar.kt
  core/designsystem/src/main/res/values/themes.xml
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetCharacterViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SplashScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/ShowSetCharacterPager.kt
  feature/auth/src/main/res/drawable-xhdpi/ic_splash_logo.png
  feature/auth/src/main/res/drawable-xxhdpi/ic_splash_logo.png
  feature/auth/src/main/res/drawable/ic_splash_logo.png
  feature/auth/src/main/res/drawable/ic_splash_logo.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreAppBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/model/UsersAdventuresInformationsEntity.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/data/remote/response/UsersAdventuresInformationsResponseDto.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/domain/model/UsersAdventuresInformations.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/MypageRoute.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MypageNavigation.kt
Labels: 🍯 feature, 🐤 참새파 준서

#89 feature: 앱 아이콘, 네임 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/offroad_logo_light.xml
  app/src/main/res/values/strings.xml
Labels: 🍯 feature, 🐴 말왕파 석찬

#91 feature: 탐험에서 홈 뷰 이동 구현 및 디자인 일부 리팩토링
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/di/UseCaseModule.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/mapper/ExploreMapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/request/ExploreLocationAuthRequestDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/request/ExploreQrAuthRequestDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/ExploreLocationAuthResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/response/ExploreQrAuthResponseDto.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/remote/service/ExploreService.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/data/repository/ExploreRepositoryImpl.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/ExploreLocationResult.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/model/ExploreQrResult.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/repository/ExploreRepository.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/PostExploreLocationAuthUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/domain/usecase/PostExploreQrAuthUseCase.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSuccessDialogItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeRoute.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/CloseCompleteQuest.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/LinearProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/quest/progressbar/RecentQuest.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
Labels: 🍯 feature, ✨ 북두파 정현, 🐤 참새파 준서

#101 feature: Add splash animation
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SplashScreen.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#105 refactor: 닉네임 중복 버튼 ux 개선
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
Labels: ♻️ refactor, 🐴 말왕파 석찬

#103 refactor: 카메라 뷰 백그라운드 상자 높이조절
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCamera.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCameraNavigateBack.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCameraOverlay.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#100 feature: 뒤로가기 두 번 클릭시 앱 종료
  core/common/build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/util/OnBackButtonListener.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/MyPageScreen.kt
Labels: 🍯 feature, 🐤 참새파 준서

#102 refactor: Adjust auto sign in delay
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/AuthScreen.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#106 refactor: Edit lottie character size
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#108 refactor: 화면 전환 애니메이션 조정
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/FadeInWrapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeRoute.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#110 refactor: Add explore failure image
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/res/drawable-xhdpi/img_explore_failed_character.png
  feature/explore/src/main/res/drawable-xxhdpi/img_explore_failed_character.png
  feature/explore/src/main/res/drawable/img_explore_failed_character.png
  feature/explore/src/main/res/values/strings.xml
Labels: ♻️ refactor, 🐤 참새파 준서

#109 docs: 리드미 작성
  README.md
Labels: 📄 docs, 🐴 말왕파 석찬, 🐤 참새파 준서

#112 Feature: 캐릭터 선택 이미지 크기 추가
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SelectedCharacterScreen.kt
  feature/auth/src/main/res/drawable/img_test_character.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
Labels: 🍯 feature, ✨ 북두파 정현

#116 refactor: Change performance of component
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/StaticAnimationWrapper.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainBottomBar.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#118 refactor: 퀘스트 진행도 및 칭호 변경
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/ErrorMessage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/UiState.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/character/CharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/ChangeEmblemDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/SelectedEmblemState.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/ErrorMessageModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/UserChangeEmblemDialogStateModel.kt
Labels: ♻️ refactor, ✨ 북두파 정현, 📄 QA 대응

#119 refactor: 1차 QA 반영
  feature/auth/src/main/java/com/teamoffroad/feature/auth/data/di/UseCaseModule.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetBirthDateValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetNicknameValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetGenderViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetNicknameViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameHintText.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameTextField.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/NicknameValidateResult.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/OnboardingButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/SetNicknameButton.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/ShowSetCharacterPager.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/NicknameUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetBirthDateUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetGenderUiState.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/model/SetNicknameUiState.kt
  feature/auth/src/main/res/values/strings.xml
Labels: ♻️ refactor, 🐴 말왕파 석찬, 📄 QA 대응

#127 refactor: 네비게이션 스택정리
  core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/navigation/AuthNavigation.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/teamoffroad/feature/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreCameraScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreCameraNavigateBack.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreFailedDialogItem.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreResultDialog.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/component/ExploreSuccessDialogItem.kt
  feature/explore/src/main/res/values/strings.xml
  feature/home/src/main/java/com/teamoffroad/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeRoute.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavTab.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainNavHost.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/component/MainTransparentActionBar.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/navigation/MypageNavigation.kt
  gradle/libs.versions.toml
Labels: ♻️ refactor, 🐤 참새파 준서, 🚨 Emergency

#128 refactor: 생년월일 포커스 이동
  feature/auth/src/main/java/com/teamoffroad/feature/auth/domain/usecase/GetBirthDateValidateUseCase.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateScreen.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/SetBirthDateViewModel.kt
  feature/auth/src/main/java/com/teamoffroad/feature/auth/presentation/component/BirthDateTextField.kt
Labels: ♻️ refactor, 🐴 말왕파 석찬, 📄 QA 대응
