Repository Team-Offroad/Offroad-Android, pull requests merged in 2025-04, with the labels that each got.

#353 feature: 강제 업데이트
  core/common/src/main/java/com/teamoffroad/core/common/data/di/NetworkModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/RepositoryModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/di/UseCaseModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/mapper/MinSupportedVersionMapper.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/model/MinSupportedVersionEntity.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/remote/response/MinSupportedVersionResponseDto.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/remote/service/MinSupportedVersionService.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/repository/MinSupportedVersionRepositoryImpl.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/model/MinSupportedVersion.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/repository/MinSupportedVersionRepository.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/usecase/MinSupportedVersionUseCase.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/teamoffroad/feature/main/AppUpdateDialog.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainScreen.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainViewModel.kt
  feature/main/src/main/res/values/strings.xml
Labels: 🍯 feature, ✨ 북두파 정현

#356 refactor: 다이어리 hexCode 반영하는 속도 개선
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/MemoryLightScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/OrbDiary.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/DiaryViewModel.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#351 refactor: 마이페이지 상단 컴포넌트 위치 조정
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/MyPageScreen.kt
Labels: ♻️ refactor, 🐤 참새파 준서

#359 fix: 지도 권한 분기 수정
  .idea/compiler.xml
  .idea/misc.xml
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
Labels: 🔨 fix, 🐤 참새파 준서
