Repository Team-Offroad/Offroad-Android, pull requests merged in 2025-03, with the labels that each got.

#335 feature: 일기 캘린더 날짜 picker
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryCalendarPicker.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHeader.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintDialog.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintFirstScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintProgressIndicator.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintSecondScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryTimeBottomSheet.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/MemoryLightScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/OrbDiary.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/OrbDiaryEmpty.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/TimeSettingDialog.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/DiaryScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/DiaryViewModel.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/model/DiaryUiState.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/util/DiaryDateRegexConverter.kt
  feature/diary/src/main/res/values/string.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/DiaryTimeDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/DiaryTimePicker.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/diaryTime/DiaryTimeScreen.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#333 feature: 기억빛 ui
  .idea/other.xml
  feature/diary/build.gradle.kts
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryCalendarPicker.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHeader.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintDialog.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintFirstScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintProgressIndicator.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryHintSecondScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/DiaryTimeBottomSheet.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/MemoryLightScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/OrbDiary.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/OrbDiaryEmpty.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/TimeSettingDialog.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/DiaryScreen.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/DiaryViewModel.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/model/DiaryHintDialogState.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/model/DiaryUiState.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/model/MemoryLight.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/util/DiaryDateRegexConverter.kt
  feature/diary/src/main/res/drawable/ic_diary_memory_light_share.xml
  feature/diary/src/main/res/drawable/ic_diary_memory_light_today_recommend.xml
  feature/diary/src/main/res/values/string.xml
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/DiaryTimeDialog.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/component/DiaryTimePicker.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/diaryTime/DiaryTimeScreen.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#323 refactor: home 모듈 내부 컴포넌트 정리
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeChangeEmblemDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeCharacterItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeCompleteQuestDialog.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeDialogCloseButton.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeDialogConfirmButton.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeDialogScrollBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeDialogTagItem.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeErrorMessage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeIcons.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestCircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestCloseComplete.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestContents.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestLinearProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestRecent.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestTitle.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeSelectedEmblemState.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeUploadImage.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeUserNicknameText.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/dialog/SelectedEmblemState.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/DownloadResult.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/HomeCharacterChatModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/HomeDownloadResult.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/HomeErrorMessageModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/model/HomeUserChangeEmblemDialogStateModel.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#325 refactor: character chat 모듈 리팩토링
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatButton.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatHeader.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatTextBox.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatTextField.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChatTimeLabel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChats.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterDateDivider.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/ImePadding.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainCharacterChat.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainUserChat.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/MainUserChatTextField.kt
Labels: ♻️ refactor, ✨ 북두파 정현

#342 refactor: modifier 오류 수정
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestCircleProgressBar.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestCloseComplete.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestContents.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/component/HomeQuestRecent.kt
Labels: 🔨 fix, ✨ 북두파 정현, 📄 QA 대응

#336 fix: 첫 채팅 보낼시 오류 해결
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/component/CharacterChats.kt
Labels: 🔨 fix, 🐤 참새파 준서

#337 docs: 이슈 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/default_issue_template.md
  .github/pull_request_template.md
Labels: 📄 docs, 🐤 참새파 준서

#352 docs: 리드미 내용 수정
  README.md
Labels: 📄 docs, 🐤 참새파 준서

#349 feature: 다이어리 FCM 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamoffroad/offroad.app/OffRoadMessagingService.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/model/FcmNotificationKey.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/model/NotificationEvent.kt
  core/designsystem/src/main/java/com/teamoffroad/core/designsystem/component/OrbDialog.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/presentation/DiaryViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/main/src/main/java/com/teamoffroad/feature/main/FcmBroadcastReceiver.kt
  feature/main/src/main/java/com/teamoffroad/feature/main/MainActivity.kt
  feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/diaryTime/DiaryTimeScreen.kt
Labels: 🍯 feature, 🐴 말왕파 석찬

#340 feature: 앱 내에 앰플리튜드 추가
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  core/common/build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/data/di/TrackerModule.kt
  core/common/src/main/java/com/teamoffroad/core/common/data/tracker/AmplitudeTracker.kt
  core/common/src/main/java/com/teamoffroad/core/common/domain/tracker/Tracker.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/CharacterChatViewModel.kt
  feature/characterchat/src/main/java/com/teamoffroad/characterchat/presentation/MainCharacterChatViewModel.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreScreen.kt
  feature/explore/src/main/java/com/teamoffroad/feature/explore/presentation/ExploreViewModel.kt
  feature/home/src/main/java/com/teamoffroad/feature/home/presentation/HomeScreen.kt
  gradle/libs.versions.toml
Labels: 🍯 feature, 🐤 참새파 준서

#354 feature: 기억빛 내보내기
  core/common/build.gradle.kts
  core/common/src/main/java/com/teamoffroad/core/common/data/tracker/AmplitudeTracker.kt
  core/common/src/main/java/com/teamoffroad/core/common/util/BitmapUtil.kt
  feature/.DS_Store
  feature/diary/.DS_Store
  feature/diary/src/.DS_Store
  feature/diary/src/androidTest/java/com/teamoffroad/feature/diary/ExampleInstrumentedTest.kt
  feature/diary/src/main/java/com/teamoffroad/feature/diary/component/MemoryLightScreen.kt
  feature/diary/src/test/java/com/teamoffroad/feature/diary/ExampleUnitTest.kt
Labels: 🍯 feature, 🐴 말왕파 석찬
